name: dr-dani.com
favicon: null
layout_spectrum: 0.6809869681019336
typography_spectrum: 0.33506970200687647
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4588742123451084
  lightness: 0.37954635033383965
  saturation: 0.0856899234931916
  rhythmicContrast: 0.8805706773418933
purpose: []
